name: Docker Image CI

on:
  push:
    branches: [ main ]
    # Publish `v1.2.3` tags as releases.
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      id: build
      run: |
        REPONAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' )
        DOCKER_IMAGE=ghcr.io/$REPONAME
        IMAGE_VERSION=$(date +%s)
        docker build . --file Dockerfile --tag $DOCKER_IMAGE:IMAGE_VERSION
        echo ::set-output name=IMAGE_VERSION::${IMAGE_VERSION}
        echo ::set-output name=DOCKER_IMAGE::${DOCKER_IMAGE}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.build.outputs.DOCKER_IMAGE }}:${{ steps.build.outputs.IMAGE_VERSION }}
