name: Docker Image CI

on:
  push:
    tags: [ v* ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Preparing variables
      id: prepare
      run: |
        REPONAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' )
        DOCKER_IMAGE=ghcr.io/$REPONAME
        # IMAGE_VERSION=$(date +%s)
        IMAGE_VERSION=${GITHUB_REF#refs/*/}
        echo ::set-output name=IMAGE_VERSION::${IMAGE_VERSION}
        echo ::set-output name=DOCKER_IMAGE::${DOCKER_IMAGE}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.prepare.outputs.DOCKER_IMAGE }}:${{ steps.prepare.outputs.IMAGE_VERSION }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    # This ugly bit is necessary if you don't want your cache to grow forever
    # till it hits GitHub's limit of 5GB.
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
