name: Docker Image CI

on:
  push:
    tags: [ v* ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Preparing variables
      id: prepare
      run: |
        REPONAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' )
        DOCKER_IMAGE=ghcr.io/$REPONAME
        # IMAGE_VERSION=$(date +%s)
        IMAGE_VERSION=${GITHUB_REF#refs/*/}
        echo ::set-output name=IMAGE_VERSION::${IMAGE_VERSION}
        echo ::set-output name=DOCKER_IMAGE::${DOCKER_IMAGE}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.prepare.outputs.DOCKER_IMAGE }}:${{ steps.prepare.outputs.IMAGE_VERSION }}
